apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: no-aliance-l3
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
