apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: fuck-aliance
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
