apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  labels:
    for: mash-mesh
    type: istio
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    path: istio-base/helm
    repoURL: https://github.com/MashMesh-cloudbro/bumgu.git
    targetRevision: main
