apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  labels:
    for: mash-mesh
    type: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.12.0
    chart: kube-prometheus-stack
    helm:
      releaseName: my-prometheus
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
