grafana:
  replicas: 1

  ## Expose the grafana service to be accessed from outside the cluster (LoadBalancer service).
  ## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
  ## ref: http://kubernetes.io/docs/user-guide/services/
  ##
  service:
    enabled: true
    type: ClusterIP

  serviceMonitor:
    ## If true, a ServiceMonitor CR is created for a prometheus operator
    ## https://github.com/coreos/prometheus-operator
    ##
    enabled: true

  ingress:
    enabled: false

  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  # Administrator credentials when not using an existing secret (see below)
  adminUser: admin
  adminPassword: strongpassword
